name: publish

on: [push]

jobs:
  publish-shamal-db-image:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the postgres:14 Docker image
      run: |
        docker build . --tag ghcr.io/Fischerskii/docker-shamal-db:latest
        docker run ghcr.io/Fischerskii/docker-shamal-db:latest
        docker push ghcr.io/Fischerskii/docker-shamal-db:latest
